/* ============================================================
   THE 25 MOST INFLUENTIAL DALLAS RECORDING ARTISTS
   Content adapted from the D Magazine print feature (July 2026).
   Essays restored/condensed from the article. Edit freely.
   ============================================================ */

window.FEATURE = {
  kicker: "A Love Letter to People in Our Ears",
  title: ["The 25 Most", "Influential", "Dallas Recording", "Artists"],
  titleFlat: "The 25 Most Influential Dallas Recording Artists",
  subtitle: "of the Last 25 Years",
  byline:
    "By Mike Marshall, Bethany Erickson, Jeff \u201cSkin\u201d Wade, Pete Freedman, Bobby Sessions, Chris Holt, Josh Campbell, Kevin Turner, and Jason Janik",
  issue: "D Magazine \u2014 July 2026",
  // Drop a hero film here (YouTube ID or a local mp4 path). Leave null for the placeholder state.
  heroVideo: "61efa440cc230ba46978aa576bd20b25",
};

window.INTRO = {
  heading: "Why does it matter where music comes from?",
  byline: "Mike Marshall",
  hasVideo: true,
  body: [
    "Maybe to you, it doesn\u2019t. In which case, what a blissfully ignorant life you must lead\u2014never wondering what the origin story of \u201CPossum Kingdom\u201D is (it\u2019s not about a murder on the lake) or asking what The D.O.C. refers to (Dallas Oak Cliff). After all, great art can be appreciated at different depths. You don\u2019t need to know that \u201CBoys of Summer\u201D was originally written for Tom Petty by his guitarist Mike Campbell to understand it absolutely slaps.",
    "But I do. I need to know everything. I\u2019ve always had a curiosity for what environment molded the art in front of me. What has the artist lived through? What did it cost to get here? If they\u2019re from the same place as I am, what are they seeing that I can\u2019t? More critically, are they saying anything that hasn\u2019t been said before, or making a sound that hasn\u2019t yet become hack? For the artists on this list, the answers to all of those questions were influenced by Dallas. In turn, you can find a piece of Dallas in how they\u2019ve influenced the world around them.",
    "So when the subject of Dallas culture began circulating around our office, I turned the conversation to music. I wanted to examine\u2014and celebrate\u2014what our city has put into the world. And, in classic insecure Dallas fashion, I also needed to know how our best musicians measure up to those from other cities. That\u2019s how we got here: our list of the 25 Most Influential Dallas Recording Artists of the Last 25 Years.",
    "Why 25? It felt right. 2000 through 2025 takes us from pre-music-on-the-internet to post-website, which provides a remarkable pool to choose from. (With a couple of exceptions, an artist had to have been active within the last 25 years to be eligible.) A task this ambitious required a methodology. It also needed an esteemed team of 12 judges. They were asked to nominate 30 artists they believed were important to Dallas over the last quarter century. That produced a list of 102 nominees, from which each judge chose their top 25. Then I calculated the average ranking of each artist to arrive at our final list.",
  ],
};

/* genre keys used by the filter chips */
window.GENRES = [
  "Soul / R&B",
  "Hip-Hop",
  "Rock",
  "Country",
  "Jazz",
  "Pop",
  "Gospel",
  "Experimental",
];

window.ARTISTS = [
  {
    rank: 1,
    photo: "uploads/Erykah Badu.jpg",
    name: "Erykah Badu",
    genre: "Neo-Soul",
    era: "1997\u2013present",
    place: "South Dallas",
    writer: "Jeff \u201cSkin\u201d Wade",
    hasVideo: true,
    video: "17e0bba95bbca5a663d14517f620984c",
    featured: true,
    credit: "Photograph \u2014 Adam McCulough",
    pull: "That\u2019s what one song can do for a city.",
    body: [
      "I didn\u2019t know who she was when she came home from Grambling State and reintegrated herself into our local rap scene. But the cats who had been around much longer than I had? They all knew Erykah Badu. She didn\u2019t seem like other female R&B artists of the time, and she didn\u2019t seem like a rapper either. But she had a vibe\u2014effortless, casual, and way too special to be spending any time around someone like me.",
      "For a while, Erykah co-hosted a weekly freestyle gig with us at a Lower Greenville spot called Rebounds. When she took the mic and threw down Billie Holiday\u2013inspired scat verses over Roots instrumentals, it felt perfect. Every dude who made beats around town wanted to work with her. She even had a cool duo act going with her cousin Rob Free\u2014Erykah Free, as they were called, back when acid jazz was a thing.",
      "What I remember even more was the time Kassan Da\u2019 Don, of local rap group Mad Flava, played me a beat-tape of a young local producer we all respected named Jah Born. One beat stood out, with its chopped-up jazzy pianos and minimal, rimshot-flavored beat. What I could never have imagined was that the beat would get attached to that hip Southern girl and become \u201COn and On,\u201D the track that would spawn a revolution in and out of Dallas. That\u2019s what one song can do for a city\u2014at least when that song is made by Erykah Badu.",
    ],
  },
  {
    rank: 2,
    photo: "uploads/St-Vincent.jpg",
    name: "St. Vincent",
    genre: "Rock",
    era: "2007\u2013present",
    place: "Lake Highlands",
    writer: "Mike Marshall",
    hasVideo: true,
    video: "3bc8449caba30537f99506fe794583de",
    featured: false,
    pull: "Music from a not-so-distant future you don\u2019t fully comprehend yet.",
    body: [
      "I\u2019ve been in love with Annie Clark (metaphorically and musically, if my wife is reading) for so long that I had forgotten when the switch flipped from knowing she\u2019s an adorable artist out of Lake Highlands to comprehending that Dallas produced one of the most intriguing musicians on earth. A simple re-listen made me remember in a hurry.",
      "Take her album Strange Mercy. Good God almighty, what a collection of absurdly beautiful arrangements. For me, that was the moment Clark realized her ability to take on any character from the lyrical side. The music had always been there, but the world-building was new.",
      "One of the many things I admire about Clark is that she\u2019s an old-school rock-and-roll frontwoman who leaves blood on the track. As St. Vincent, she has absolutely zero fear of being creepy, grotesque, sexy, or overtly horny in order to bend the mirror. Her records often feel like music from a not-so-distant future you don\u2019t fully comprehend yet. The way I measure greatness is, \u201CWas the community attempting to replicate this feat in the years following its arrival?\u201D The music industry has been trying to replicate Strange Mercy for 15 years now. Nobody has gotten close.",
    ],
  },
  {
    rank: 3,
    photo: "uploads/Norah Jones.jpg",
    name: "Norah Jones",
    genre: "Jazz",
    era: "2002\u2013present",
    place: "Grapevine",
    writer: "Bethany Erickson",
    hasVideo: false,
    featured: false,
    pull: "Art is meant to be played with.",
    body: [
      "Before Norah Jones invited everyone to \u201CCome Away With Me,\u201D she was a student at Booker T. Washington High School for the Performing and Visual Arts, walking the halls with the likes of Kirk Franklin\u2019s music director, the late Shaun Martin, and Erykah Badu collaborator RC Williams. Before that, there was a brief stint at Grapevine High, where she played saxophone in the marching band. She\u2019d go on to UNT, also known for churning out excellent, Grammy-winning musicians.",
      "Jones\u2019 first album dropped not long after she graduated. It burst onto the charts seemingly with the velocity of a one-hit wonder\u2014in truth, it didn\u2019t chart until a full year after its release\u2014but with the enduring power of something far more legendary.",
      "In the years since, she has shown a willingness to switch it up, whether it be genre, instruments, or collaborators, including Willie Nelson, Mavis Staples, Foo Fighters, Questlove, and OutKast. This year, the Grammy Museum gave her the Ray Charles Architect of Sound Award. She has not visited North Texas often since she packed up for New York, but ask anyone here and there\u2019s never any doubt: she\u2019s a vital part of the region\u2019s artistic fabric.",
    ],
  },
  {
    rank: 4,
    photo: "uploads/Leon Bridges.jpg",
    name: "Leon Bridges",
    genre: "Soul / R&B",
    era: "2014\u2013present",
    place: "Fort Worth",
    writer: "Jeff \u201cSkin\u201d Wade",
    hasVideo: false,
    featured: false,
    pull: "Turns out Leon Bridges didn\u2019t need any help from us.",
    body: [
      "In the fall of 2014, Chris Cantalini from the influential blog Gorilla vs. Bear emailed me and Danny Balis a SoundCloud link for a dude out of Fort Worth who was doing vintage soul. Not like the \u201960s retro funk and R&B that the Brooklyn-based Daptone folks were trailblazing with\u2014more that smooth Sam Cooke style. It was expertly tracked, and Leon Bridges\u2019 voice and songs were tailor-made for the approach.",
      "Turns out Leon Bridges didn\u2019t need any help from us. A mere two months later, Leon had a huge buzz and was performing a New Year\u2019s Eve show on the small side of Gypsy Tea Room. At that point he still had three background singers and they were calling themselves Leon and the Chandeliers. RC Williams was there, and I asked him how this guy came out of nowhere. \u201CNaw, man, he\u2019s been around the church scene for a while,\u201D Williams told me. \u201CWe all know him.\u201D",
      "A few months after that, the whole world knew Leon. He picked up an Apple commercial and a huge debut record on Columbia. He toured the world, mixed and matched genres, and became a Grammy Award\u2013winning star. And eight years after that email, Balis and I got to collaborate with Leon on a cover of the gospel R&B classic \u201CLike a Ship.\u201D Chris must\u2019ve known what he was doing.",
    ],
  },
  {
    rank: 5,
    photo: "uploads/Old 97s.jpg",
    name: "Old 97\u2019s",
    genre: "Americana",
    era: "1993\u2013present",
    place: "Deep Ellum",
    writer: "Jeff \u201cSkin\u201d Wade",
    hasVideo: false,
    featured: false,
    pull: "Great bands that rep their scene never go out of style.",
    body: [
      "They cut their teeth in the smoky bars of Deep Ellum\u2019s supposed \u201990s heyday, but confine the Old 97\u2019s to that era at your own peril. Some of the band\u2019s best work dropped in the \u201910s, and nine of the group\u2019s 13 studio LPs were released within the last 25 years. Oh, and lest anyone forget: it was 20 years ago this summer that an Old 97\u2019s live show served as a pivotal scene in the 2006 Jennifer Aniston\u2013Vince Vaughn vehicle The Break-Up.",
      "Rhett, Murry, Ken, and Philip have persisted at a clip that bands half their age only daydream about. Better still, the 97\u2019s have always harnessed their national fandom for local good. From 2016 to 2018, the band partnered with the Homegrown Music & Arts Festival team to host the Old 97\u2019s County Fair, an annual daylong affair that welcomed alt-country luminaries including Lucinda Williams, Drive-By Truckers, and The Jayhawks to downtown Dallas.",
      "Each of those bashes made a point to showcase who was coming up behind them in Deep Ellum, with next-up names such as Paul Cauthen, Bastards of Soul, and The Texas Gentlemen getting their time to shine. The first half of the Old 97\u2019s name may now bear a more literal meaning, but great bands that spread the wealth and rep their scene so well never go out of style.",
    ],
  },
  {
    rank: 6,
    photo: "uploads/The Toadies.jpg",
    name: "Toadies",
    genre: "Rock",
    era: "1989\u2013present",
    place: "Fort Worth",
    writer: "Josh Campbell",
    hasVideo: false,
    featured: false,
    pull: "A testament to a love that never died.",
    body: [
      "In 1994, Toadies\u2019 debut album Rubberneck thrust the band and North Texas into national relevance. Maybe we weren\u2019t Seattle, but we were making worthy contributions to the rebellious rock movement of the time, and Toadies were our champion. It came to a bitter end seven years later: Interscope rejected the band\u2019s second album, Feeler, and withheld promotion for Hell Below/Stars Above. Bassist Lisa Umbarger resigned, and Toadies were no more.",
      "Five years passed and the region\u2019s love for the group wouldn\u2019t fade. Band or no band, Toadies\u2019 songs refused to drop off radio rotation. So perhaps it shouldn\u2019t have been surprising when a reunion show at the Greenville Avenue St. Patrick\u2019s Day Parade mushroomed from a one-off to a tour to plans for a new album.",
      "They released No Deliverance under a new label and hosted their inaugural self-organized festival, Dia de los Toadies, which showcased Dallas-area artists such as the Old 97\u2019s, Oil Boom, Ben Kweller, Centro-Matic, Secret Machines, Sarah Jaffe, and The O\u2019s. The band\u2019s eighth album was released earlier this year. Consider it a testament to a love that never died.",
    ],
  },
  {
    rank: 7,
    photo: "uploads/The-Chicks.jpg",
    name: "The Chicks",
    genre: "Country",
    era: "1989\u2013present",
    place: "Dallas",
    writer: "Jeff \u201cSkin\u201d Wade",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Peter Serocki",
    pull: "It was clear they were really good.",
    body: [
      "In 1990, I was working at the Sound Warehouse on Greenville Avenue when an up-and-coming regional act known as The Dixie Chicks was scheduled for an in-store performance. Martie and Emily Erwin walked in all made up and decked out in their jeans, hats, and boots. The sisters were confident and about their business, but there wasn\u2019t a hint of self-import or big-time attitude. They carried their own instrument cases.",
      "When the duo got situated and started playing, it was clear they were really good. I didn\u2019t know their songs, nor how popular they were, and none of that was necessary to grasp that they had presence.",
      "Years later, the sisters\u2014along with new lead singer Natalie Maines\u2014had become one of the biggest bands on the planet. The name may be different now, but with more than 30 million albums sold worldwide, The Chicks\u2019 status as an iconic North Texas band remains the same as it ever was.",
    ],
  },
  {
    rank: 8,
    photo: "uploads/Post-Malone.jpg",
    name: "Post Malone",
    genre: "Hip-Hop",
    era: "2015\u2013present",
    place: "Grapevine",
    writer: "Pete Freedman",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Ben Houdijk",
    pull: "That\u2019s the definition of influence.",
    body: [
      "Forget for a moment that, per most available metrics, he is one of the most-streamed artists ever on Spotify. Disregard that he has recorded duets with both Taylor Swift and Beyonc\u00E9\u2014on their albums, no less. Never mind that he\u2019s the level of celebrity who gets interviewed by late-night talk show hosts instead of just being asked to perform.",
      "Want the clearest sign that the Grapevine-sprung Post Malone is already one of the most influential artists North Texas has ever produced? Let\u2019s talk beer. Jerry Jones made several bold moves after purchasing the Cowboys, including making Miller Lite the team\u2019s official beer sponsor. Budweiser drinkers were SOL on Cowboys grounds\u2014except for one day in November, anyway.",
      "That day, Post Malone\u2019s annual Posty Fest was held at AT&T Stadium, and Jones\u2014this one time\u2014allowed Bud Light to be prominently served at Jerry World. Why the exception? Because Post Malone, whose father once ran concessions at AT&T Stadium, has an exclusive beer partnership of his own. To secure a fully Post Malone\u2013approved offering, the famously hard-line Jerry bent the knee. That\u2019s the definition of influence.",
    ],
  },
  {
    rank: 9,
    photo: "uploads/The-DOC.jpg",
    name: "The D.O.C.",
    genre: "Hip-Hop",
    era: "1989\u2013present",
    place: "West Dallas",
    writer: "Bobby Sessions",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Jaguar PS",
    pull: "He gave the people we look up to somebody they looked up to.",
    body: [
      "Straight out of West Dallas, The D.O.C. became one of the architects and pioneers who shaped West Coast hip-hop through his work with N.W.A and his legendary solo album No One Can Do It Better.",
      "But that wasn\u2019t all. Music speaking on racial injustice, police brutality, and the raw realities happening in the neighborhood often carried his pen. He provided narration and play-by-play commentary on what our people were experiencing in real time. From his work with Dr. Dre to influencing Eminem to teaching Snoop Dogg how to rap, he gave the people we look up to somebody they looked up to.",
      "I\u2019m no exception. I felt The D.O.C.\u2019s impact deeply when recording my RVLTN series upon signing with Def Jam in 2017. I laced that music with sociopolitical commentary, and I remain unafraid to address issues in a raw, unapologetic way. Extreme circumstances require extreme language. The D.O.C. helped set that standard, and\u2014like so many other things\u2014no one could do it better than him.",
    ],
  },
  {
    rank: 10,
    photo: "uploads/Kirk-Franklin.jpg",
    name: "Kirk Franklin",
    genre: "Gospel",
    era: "1993\u2013present",
    place: "Fort Worth",
    writer: "Bethany Erickson",
    hasVideo: false,
    featured: true,
    credit: "Photograph \u2014 D\u2019Avril Grant",
    pull: "I can\u2019t afford for you to forget me.",
    body: [
      "Raised in the church before his feet could touch the floor from the pews, Kirk Franklin began playing piano at 4. By 11 he was leading a choir of adults at Fort Worth\u2019s Mount Rose Baptist Church. He\u2019d go on to attend O.D. Wyatt High, studying with gospel music director and Fort Worth educator Jewel Kelly. At 17 he had his first gospel group, the Humble Hearts.",
      "Franklin formed The Family in 1992 and produced the first gospel album ever to earn platinum certification, propelled in part by the success of \u201CWhy We Sing.\u201D The group God\u2019s Property came three years later and would create a sound that seamlessly blended praise and worship with funk and hip-hop, even bringing in Cheryl \u201CSalt\u201D James of Salt-N-Pepa to make the enduring \u201CStomp\u201D remix that later sat atop the R&B and hip-hop charts.",
      "Decades later, Franklin\u2019s career continues to thrive and influence. \u201CThere is no secret sauce,\u201D he told WFAA, \u201Cbut I tell you, if you want to know my motivation and what drives me\u2014I can\u2019t afford for you to forget me.\u201D",
    ],
  },
  {
    rank: 11,
    photo: "uploads/TBone-Burnett.jpg",
    name: "T-Bone Burnett",
    genre: "Rock",
    era: "1972\u2013present",
    place: "Fort Worth",
    writer: "Bethany Erickson",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Joe Seer",
    pull: "You may not know his face, but you know his sound.",
    body: [
      "Before he was a guitarist in Bob Dylan\u2019s band, a Grammy winner, and the guy who gave some of the best-known names in music their start, T-Bone Burnett was Joseph Henry Burnett III, born in St. Louis and raised in Fort Worth, where his dad worked for Tandy Corp. after a brief flirtation with professional baseball.",
      "Thanks to his parents, he came up on a wide array of music, everything from Louis Armstrong and Mahalia Jackson to Hank Williams and The Beatles. But he can thank childhood friend Stephen Bruton for his interest in bluegrass; the two spent time listening to the genre and sneaking into Fort Worth clubs.",
      "While he has done his share of writing and producing for other artists and on movie soundtracks, Burnett has spent the last several years making and touring behind his own music. \u201CI\u2019ve always been a behind-the-scenes person. I like creating in private,\u201D he told CBS, copping to the \u201Cinsecurity\u201D that prevented him from performing. But while you may not know his face, five decades of songwriting mean you know his sound.",
    ],
  },
  {
    rank: 12,
    photo: "uploads/Don-Henley.jpg",
    name: "Don Henley",
    genre: "Rock",
    era: "1971\u2013present",
    place: "Linden / Dallas",
    writer: "Chris Holt",
    hasVideo: false,
    featured: true,
    credit: "Photograph \u2014 Kelly Rogers/Press Journal",
    pull: "It\u2019s always, first and foremost, about the song.",
    body: [
      "As the guitarist of his touring band, I can tell you that the bottom line with Don is that it\u2019s always, first and foremost, about the song. Lyrics are every bit as important as melody and harmony. He wants the song to be about something, and he carefully ponders each line\u2014the sound and meaning\u2014whether he\u2019s painting a haunting landscape of dystopian western life, waxing wistfully nostalgic about a long-lost love, or sniping at the superficialities of modern society.",
      "And the songs speak for themselves, don\u2019t they? Everybody knows them, whether you love them or not. His imagery, his beats, that wonderfully raspy tenor\u2014it\u2019s virtually everywhere, all the time. He\u2019s forever ingrained in our collective musical consciousness. And it\u2019s not luck or by accident.",
      "Don has a reputation for being a no-nonsense guy, which some take as grumpy, but that\u2019s not fair. He never stops caring about getting it right, and he expects everyone to play at that same level every time they step into the studio or onto the stage. It\u2019s what makes him one of the best ever at what he does. That, and a pair of the highest-selling albums in history. Even \u201CThe Dude\u201D can\u2019t deny that.",
    ],
  },
  {
    rank: 13,
    photo: "uploads/Big-Tuck.jpg",
    name: "Big Tuck",
    genre: "Hip-Hop",
    era: "2004\u2013present",
    place: "South Dallas",
    writer: "Bobby Sessions",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Cedric Tuck",
    pull: "You get a real sense of pride when you see people from your hometown moving like that.",
    body: [
      "When I was in school, Big Tuck probably had the same level of impact on me as Jay-Z. The flow he used on \u201CSouthside Da Realist\u201D became the foundation all of us had when we rapped at the lunch table, in the locker room, on the bus, in the car.",
      "At a summer camp one year at Exline Recreation Center in South Dallas, they were shooting a music video around the area. I saw Big Tuck and the whole group, Dirty South Rydaz, and I saw somebody pull out one of the biggest stacks of cash I had ever seen in my life. I thought that was the coolest thing in the world. You get a real sense of pride when you see people from your hometown moving like that.",
      "So to this day, when I go freestyle, I\u2019m going to say my name, I\u2019m going to say where I\u2019m from, and I\u2019m going to say what car I\u2019m pulling up in. I can thank the one and only Big Tuck for that.",
    ],
  },
  {
    rank: 14,
    photo: "uploads/Polyphonic-Spree.jpg",
    name: "The Polyphonic Spree",
    genre: "Rock",
    era: "2000\u2013present",
    place: "Dallas",
    writer: "Kevin Turner",
    hasVideo: false,
    featured: false,
    pull: "They just don\u2019t make \u2019em like The Polyphonic Spree.",
    body: [
      "The Spree\u2019s live shows are a religious experience that\u2019ll make you forget, if only for a night, that the Cowboys haven\u2019t been to a Super Bowl in 30 years. And their Holiday Extravaganza will set you right better than any ketamine session could. Credit that to more than 20 musicians from various backgrounds who coalesce to form a distinct, powerful, mesmerizing sound.",
      "Maybe the most unique band in the history of our city, what makes Tim DeLaughter\u2019s creation so distinctive is its ability to connect on a personal level with so many different people, no matter what that person might be going through. The music meets you where you are.",
      "And that goes for the band, too, which over the years has been a revolving door of some of your favorite local musicians. They just don\u2019t make \u2019em like The Polyphonic Spree. Who else would even be kooky enough to try it?",
    ],
  },
  {
    rank: 15,
    photo: "uploads/Edie-Brickell.jpg",
    name: "Edie Brickell",
    genre: "Rock",
    era: "1985\u2013present",
    place: "Oak Cliff",
    writer: "Bethany Erickson",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Paul Mann",
    pull: "It\u2019s hard to believe. That doesn\u2019t make it any less true.",
    body: [
      "So much of Edie Brickell\u2019s career sounds like legend, or possibly a fevered round of Mad Libs. Born in Oak Cliff. Attended Booker T. and SMU. The scattershot lyrics of \u201CWhat I Am\u201D with the New Bohemians, which became a smash hit when she was a mere 22 years old.",
      "Meeting Paul Simon when her band was on Saturday Night Live in 1988, then later marrying him. Solo albums, including Picture Perfect Morning, with its \u201CGood Times\u201D single that ended up on a Microsoft Windows 95 CD-ROM.",
      "Perhaps quirkiest of all, her collaborations with comedian and musician Steve Martin, including the Broadway musical Bright Star, which she reportedly got the idea for after coming across an archived newspaper story about a baby placed in a suitcase and thrown from a train. That show ended up with five Tony nominations. Like so much else with Brickell, it\u2019s hard to believe. That doesn\u2019t make it any less true.",
    ],
  },
  {
    rank: 16,
    photo: "uploads/Bowling-For-Soup.jpg",
    name: "Bowling for Soup",
    genre: "Pop Punk",
    era: "1994\u2013present",
    place: "Wichita Falls / Denton",
    writer: "Pete Freedman",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 CatchingLightPhotography",
    pull: "Earworm singalong hooks age well.",
    body: [
      "Want to feel ancient? As you read this, we\u2019re further away from when Bowling for Soup released \u201C1985\u201D than Bowling for Soup was when the single dropped in 2004. The pop-punk four-piece couldn\u2019t care less. They\u2019ve been joking about growing longer in the tooth for years.",
      "And yet, somehow, this endlessly snotty band\u2014which jumped from Wichita Falls to Denton and then into living rooms across America in the early \u201900s via seemingly constant VH1 video rotation\u2014found itself just last year telling the same ol\u2019 dick-and-fart jokes onstage to sold-out crowds at London\u2019s Wembley Arena.",
      "New generations keep finding joy in BFS, and not just because the band recorded the theme song for the Disney Channel show Phineas and Ferb, or because frontman Jaret Reddick picked up a side gig as the voice of Chuck E. Cheese. Turns out earworm singalong hooks and generationally inescapable melodies age well.",
    ],
  },
  {
    rank: 17,
    photo: "uploads/Marc-Rebillet.jpg",
    name: "Marc Rebillet",
    genre: "Experimental",
    era: "2017\u2013present",
    place: "Dallas",
    writer: "Pete Freedman",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Ben Houdijk",
    pull: "Making it up as he goes along.",
    body: [
      "In the span of a year, improvisational Dallas musician Marc Rebillet went from taking song-topic suggestions from crowds of charitably a dozen on Thursday nights at Uptown\u2019s Common Table to becoming the internet\u2019s favorite manic body-rocker, earning millions of views with each bedroom-recorded jam session he broadcasts via webcam.",
      "The world just doesn\u2019t spit out minds like Rebillet\u2019s. His funky sound is built on the foundation of a loop machine into which he feeds keyboards and drum samples, and over which he moans and shouts occasionally vulgar, always off-the-wall freestyled lyrics. His fans call him the Loop Daddy.",
      "North Texas doesn\u2019t just claim the Booker T. alum\u2014it\u2019s invested in his bizarre successes. Erykah Badu was an early fan and supporter. Just last year, Kelly Clarkson interviewed him on her daytime talk show couch. Not bad for a guy who is literally just making it up as he goes along.",
    ],
  },
  {
    rank: 18,
    photo: "uploads/Midlake.jpg",
    name: "Midlake",
    genre: "Rock",
    era: "1999\u2013present",
    place: "Denton",
    writer: "Josh Campbell",
    hasVideo: false,
    featured: false,
    pull: "A nostalgic masterpiece.",
    body: [
      "With soft, alluring melodies, layered harmonies, intimate textured rhythms, and prominently featured flutes, Midlake burst onto the scene with their second album, The Trials of Van Occupanther. At a time when rock music was running on the fumes of pop-punk and nu-metal, this collection of jazz musicians from Denton unfurled a nostalgic masterpiece, harkening to the late \u201970s era while blending rock, folk, and funk.",
      "This was just the start. Over the last 20 years, Midlake has spanned genres with care and intentionality.",
      "They\u2019ve also fostered the next wave of music inside the community from which they came. My brother Caleb is one of many Dentonites whose career is better for having known them, thanks to vocalist Eric Pulido getting his record in front of the right label.",
    ],
  },
  {
    rank: 19,
    photo: "uploads/Charley-Crockett.jpg",
    name: "Charley Crockett",
    genre: "Country",
    era: "2015\u2013present",
    place: "Dallas / San Benito",
    writer: "Mike Marshall",
    hasVideo: false,
    featured: false,
    pull: "Crockett is bona fide. He\u2019s got the hat and the cattle.",
    body: [
      "You just woke up on a spaceship shooting toward Earth from 230,000 miles away, having slingshotted around the moon. What song are you cranking? \u201CLonesome Drifter\u201D by Charley Crockett. That actually happened, with the crew of Artemis II.",
      "Crockett is bona fide. He\u2019s got the hat and the cattle. And if we\u2019re lucky, he will give voice to a new wave of \u201CGulf & Western\u201D (his term) artists. Lil GL, as he\u2019s otherwise known, needs some friends, like Waylon Jennings needed The Highwaymen.",
      "In the meantime, he\u2019ll stay busy. Between the time we started this project and when you\u2019ll read it, Crockett dropped another full-length studio album\u2014his second of the year\u2014with Shooter Jennings, Waylon\u2019s son.",
    ],
  },
  {
    rank: 20,
    photo: "uploads/Power-Trip.jpg",
    name: "Power Trip",
    genre: "Rock",
    era: "2008\u2013present",
    place: "Dallas",
    writer: "Pete Freedman",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Adam Cedillo",
    pull: "It\u2019s a goddamn masterpiece.",
    body: [
      "Should you even get a say on the most influential Dallas acts of the last 25 years if you never caught a black eye in a Power Trip pit? No Dallas-area band this side of Pantera ever could claim a more visceral live experience than what crowds face at this crossover thrash group\u2019s shows.",
      "That hasn\u2019t changed even after the passing of lead singer Riley Gale in 2020, probably because few thrash bands carry such widespread appeal. Stubborn metalheads and snobby hipsters alike appreciate the combined appeal of Power Trip\u2019s knowing, Dischord Records\u2013influenced lyrics and their head-blasting, Slayer-inspired sonic assaults.",
      "Play \u201CExecutioner\u2019s Tax (Swing of the Axe)\u201D at 11. It\u2019s a goddamn masterpiece.",
    ],
  },
  {
    rank: 21,
    photo: "uploads/Centromatic.jpg",
    name: "Centro-Matic",
    genre: "Rock",
    era: "1995\u20132014",
    place: "Denton",
    writer: "Mike Marshall",
    hasVideo: true,
    video: "3f80880fb8bb250a30bb1a75153ec74e",
    featured: false,
    pull: "Bring up a Centro album and you will quickly be their king.",
    body: [
      "If you want to sound like a ball-knower in a room full of musicians, bring up a Centro album. You will quickly be their king.",
      "Nobody ever dared to mimic the Centro-Matic sound, because if you attempted to mix lyrics about radioactive waste disposal, a voice (Will Johnson\u2019s) that would fit Joe Camel, the most unorthodox drum patterns in modern rock, and a band that could melt the paint off of a barn\u2014people would think you\u2019re insane.",
      "And Centro-Matic are, along with being a perfectly obscure, breathtaking representation of Denton.",
    ],
  },
  {
    rank: 22,
    photo: "uploads/Roy-Hargrove.jpg",
    name: "Roy Hargrove",
    genre: "Jazz",
    era: "1990\u20132018",
    place: "Dallas",
    writer: "Jason Janik",
    hasVideo: false,
    featured: false,
    pull: "The Dirk Nowitzki of the trumpet.",
    body: [
      "To put it in very Dallas terms, Roy Hargrove, who passed away in 2018, was the Dirk Nowitzki of the trumpet\u2014a Dallas giant responsible for protecting the heritage of his craft and for adapting it to the modern age.",
      "Born in Waco and raised in Dallas, the Booker T. alumnus was a multi-Grammy winner for good reason. The man had chops that were as quick as Yngwie Malmsteen\u2019s guitar licks, but he knew how to say so much more with a single note and a pause.",
      "Hargrove was a versatile performer who not only put out a long list of jazz standards but also collaborated with the likes of Boz Scaggs, Erykah Badu, and Q-Tip. For every classic hard-bop and cool-jazz track he recorded, he had an equal number of hip-hop, neo-soul, and R&B songs in his discography. Just like Dirk, the man had range.",
    ],
  },
  {
    rank: 23,
    photo: "uploads/Bobby-Sessions.jpg",
    name: "Bobby Sessions",
    genre: "Hip-Hop",
    era: "2014\u2013present",
    place: "Pleasant Grove",
    writer: "Jeff \u201cSkin\u201d Wade",
    hasVideo: false,
    featured: false,
    pull: "Bobby Sessions is just getting started.",
    body: [
      "The story goes like this. Bobby Sessions created buzz and made a name for himself throughout the North Texas scene. Bobby Sessions flashed a dope flow and serious skills when it came to crafting words. Bobby Sessions had a commanding presence and oozed confidence.",
      "Bobby Sessions dreamed of being on Def Jam. Bobby Sessions signed with Def Jam. Bobby Sessions established himself as an elite songwriter and penned a No. 1\u2013charting song that won a Grammy with Megan Thee Stallion and Beyonc\u00E9.",
      "Bobby Sessions recorded for movie soundtracks and collaborated with Marvel Comics. Bobby Sessions is the \u201CYoung Legend.\u201D Bobby Sessions is just getting started.",
    ],
  },
  {
    rank: 24,
    photo: "uploads/BigX-Tha-Plug.jpg",
    name: "BigXthaPlug",
    genre: "Hip-Hop",
    era: "2022\u2013present",
    place: "Pleasant Grove",
    writer: "Mike Marshall",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Nicole Hester/The Tennessean/USA Today",
    pull: "I\u2019m confident he\u2019ll be conducting that steam engine.",
    body: [
      "When we do this in another 25 years, I fully expect Xavier Landum\u2014aka BigXthaPlug\u2014to crack the top 5 of this list. In a rap world where it feels like it\u2019s all been done before, BigX burst through the door like a juggernaut, and his impact has permeated to the roots of Dallas urban culture just three years since his first studio album release.",
      "The vocal chain is intoxicating but still dripping with hype. The tracks are built from records buried deep down in a crate inside someone\u2019s garage. Did you know you could sample musicians like Shuggie Otis or War and flip that into a hit in the 2020s? BigX can.",
      "So whatever the future of Dallas rap is, I\u2019m confident he\u2019ll be conducting that steam engine.",
    ],
  },
  {
    rank: 25,
    photo: "uploads/Snarky-Puppy.jpg",
    name: "Snarky Puppy",
    genre: "Jazz",
    era: "2004\u2013present",
    place: "Denton (UNT)",
    writer: "Jeff \u201cSkin\u201d Wade",
    hasVideo: false,
    featured: false,
    credit: "Photograph \u2014 Brian Friedman",
    pull: "UNT\u2019s lineage of musical excellence.",
    body: [
      "No group epitomizes UNT\u2019s lineage of musical excellence quite like Snarky Puppy. Formed by Michael League in the early 2000s, the jazz-fusion group\u2019s members have included huge touring and session names.",
      "Those names include Mark Lettieri (guitar), Bobby Sparks II (keys), and percussionists Nate Werth and Sput Searight, who went on to form Ghost-Note\u2014as well as the recently deceased and highly revered Shaun Martin.",
      "They\u2019ve taken home five Grammys and rubbed elbows with the likes of Erykah Badu and Kirk Franklin.",
    ],
  },
];

window.STUDIOS = {
  intro:
    "You know the artists. What about where their music is recorded? North Texas\u2019 studio culture is among the most robust in the country, for local and national talent alike. These are the places where Dallas\u2019 sound comes from.",
  list: [
    { name: "Electric Barryland Studio", location: "Justin", op: "Jordan Richardson", artists: "Quaker City Night Hawks, Son of Stan, The Polyphonic Spree" },
    { name: "Niles City Sound", location: "Fort Worth", op: "Robert Ellis, Jimi Bowman & Jay Jernigan", artists: "Leon Bridges, Jamestown Revival, Paul Schalda" },
    { name: "The Echo Lab", location: "Argyle", op: "Matt Pence", artists: "Jason Isbell, Centro-Matic, Midlake" },
    { name: "Legacy Music Group", location: "Main St.", op: "Matthew Medlock", artists: "Post Malone, Andr\u00E9 3000, Mac Miller" },
    { name: "Luminous Sound", location: "Dallas Pkwy.", op: "Paul Loomis", artists: "Erykah Badu, Lady Gaga, Ed Sheeran" },
    { name: "Empire Sound", location: "Carrollton", op: "Alex Gerst", artists: "The House Harkonnen, Pimpadelic, Flickerstick" },
    { name: "Crystal Clear Sound", location: "Don Dr.", op: "Kent Stump", artists: "Reverend Horton Heat, Kirk Franklin, Toadies" },
    { name: "The Kitchen Studios", location: "Garland Rd.", op: "John Painter", artists: "Erykah Badu, Big Tuck, Juvenile" },
    { name: "Modern Electric Sound Recorders", location: "Dallas", op: "Jeff Saenz & Beau Bedford", artists: "Paul Cauthen, Leon Bridges, Nikki Lane" },
    { name: "Furndware Recording Studio", location: "W. Jefferson Blvd.", op: "Patrick Craine", artists: "Mark Lettieri, Eric Roberson" },
    { name: "Alpha Omega Recording Studios", location: "Fort Worth", op: "Al Gibbs", artists: "Shirley Carter, Cotinga, Quimikoz" },
  ],
};

window.JUDGES = [
  { first: "Mike", last: "Marshall", bio: "D Magazine executive producer, former Dallas Mavericks vice president, creator of many outstanding video and radio shows. The biggest Centro-Matic fan you\u2019ve ever met." },
  { first: "Bethany", last: "Erickson", bio: "D Magazine senior online editor, the proprietor of DBrief, and curator of our online concert calendar. The only mom you know who DJed an eighth-grade dance and left with rave reviews from the kids." },
  { first: "Pete", last: "Freedman", bio: "Creator of Central Track (RIP), the most influential Dallas music blog ever. He knows more about Dallas music than most people do about their credit score." },
  { first: "Will \u201CDJ Sober\u201D", last: "Rhoten", bio: "In the words of the late, great Zac Crain, \u201CHe\u2019s a load-bearing wall of North Texas nightlife, able to play anything for anyone anywhere.\u201D A multi-time winner of the Best of Big D \u201CBest DJ\u201D category." },
  { first: "Jeff", last: "Liles", bio: "Artistic director for Kessler Presents, which runs The Kessler Theater and The Longhorn Ballroom. A musician, a DJ, a writer, and the first person to ever play \u201CBoyz-n-the-Hood\u201D on the radio. The godfather of Dallas music." },
  { first: "Bobby", last: "Sessions", bio: "Def Jam artist, Grammy winner, Marvel Comics contributor, and arguably Dallas\u2019 finest modern rap export. Also a name you\u2019ll see on this list." },
  { first: "Chris", last: "Holt", photo: "uploads/Chris-Holt-2.jpg", bio: "Touring guitarist for The Eagles, sideman for Don Henley, and a Dallas music scene legend. Probably the single most qualified person to write about Henley besides the man himself." },
  { first: "Kevin", last: "Turner", bio: "On-air personality for The Ben and Skin Show on 97.1 The Eagle and co-host of the One Star Cowboys Podcast. Has attended every live performance by The Polyphonic Spree since at least 2011." },
  { first: "Jeff \u201CSkin\u201D", last: "Wade", bio: "Co-host of The Ben and Skin Show on 97.1 The Eagle, co-owner of Rollertown Beer Works, co-founder of Eastwood Music Group, and a good time in the Mavs\u2019 broadcast booth. Coolest Rolodex of anyone we know." },
  { first: "Josh", last: "Campbell", bio: "Twenty-year veteran of the local music scene, with stints in bands including Orange Peel Sunshine, I\u2019m the One Who\u2019s Fighting, and Oatmeal Pizza. Cares more about the Rangers than you do. Legally blind." },
  { first: "Tami", last: "Thomsen", bio: "Founder of Ann Arkey Productions, where she manages bands, works in events, and consults for record labels. Previously a co-founder of Last Beat Record Store, Studios, and Record Label." },
  { first: "Jason", last: "Janik", bio: "You name it, he\u2019s shot it in and around Dallas\u2014for Rolling Stone, Spin, the New York Times, and, of course, D Magazine. Owner of a very rad vinyl collection." },
];
